/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.com.Dialog;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author nguyenvan
 */
public class NgayHoc extends javax.swing.JDialog {

    /**
     * Creates new form NgayHoc
     */
    private boolean flags;
    public NgayHoc(java.awt.Frame parent, boolean modal,boolean s) {
        super(parent, modal);
        initComponents();
        flags= false;
        this.setResizable(false);
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - 200, Toolkit.getDefaultToolkit().getScreenSize().height / 2 - 150);
        if(!s){
            title.setText("Ngày nghỉ học");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        ngay = new javax.swing.JComboBox();
        thang = new javax.swing.JComboBox();
        nam = new javax.swing.JComboBox();
        chon = new javax.swing.JCheckBox();
        dongy = new javax.swing.JButton();
        huybo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Ngày nhập học của học sinh\n");

        ngay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ngày", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ngay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ngayMouseClicked(evt);
            }
        });

        thang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tháng", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        thang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thangMouseClicked(evt);
            }
        });
        thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thangActionPerformed(evt);
            }
        });

        nam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Năm", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        nam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namMouseClicked(evt);
            }
        });
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        chon.setText("Lấy thời gian hiện tại");
        chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonActionPerformed(evt);
            }
        });

        dongy.setText("Đồng ý");
        dongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongyActionPerformed(evt);
            }
        });

        huybo.setText("Hủy bỏ");
        huybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chon)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ngay, 0, 80, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(dongy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(huybo)
                        .addGap(28, 28, 28))
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chon)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dongy)
                    .addComponent(huybo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonActionPerformed
        // TODO add your handling code here:
        if (chon.isSelected()) {
            String date[] = new SimpleDateFormat("dd-MM-yyyy").format((new Date()).getTime()).split("-");
            setSelectComboBox(ngay, date[0]);
            setSelectComboBox(thang, date[1]);
            setSelectComboBox(nam, date[2]);
        }
    }//GEN-LAST:event_chonActionPerformed

    private void thangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_thangActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

    private void ngayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ngayMouseClicked
        // TODO add your handling code here:
        chon.setSelected(false);
    }//GEN-LAST:event_ngayMouseClicked

    private void thangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thangMouseClicked
        // TODO add your handling code here:
        chon.setSelected(false);
    }//GEN-LAST:event_thangMouseClicked

    private void namMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namMouseClicked
        // TODO add your handling code here:
        chon.setSelected(false);
    }//GEN-LAST:event_namMouseClicked

    private void dongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongyActionPerformed
        // TODO add your handling code here:
        if(ngay.getSelectedIndex()==0||thang.getSelectedIndex()==0||nam.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Thời gian bạn điền chưa chính xác", null,JOptionPane.ERROR_MESSAGE);
        }else{
            flags = true;
            dispose();
        }
    }//GEN-LAST:event_dongyActionPerformed

    private void huyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyboActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_huyboActionPerformed
    private void setSelectComboBox(JComboBox x, Object obj) {
        for (int i = 0; i < x.getItemCount(); i++) {
            if (x.getItemAt(i).toString().equalsIgnoreCase(obj.toString())) {
                x.setSelectedIndex(i);
                break;
            }
        }
    }
    public String getDate(){
        return nam.getSelectedItem().toString()+"-"+thang.getSelectedItem().toString()+"-"+ngay.getSelectedItem().toString();
    }
    public boolean getFlags(){
        return flags;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NgayHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NgayHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NgayHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NgayHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NgayHoc dialog = new NgayHoc(new javax.swing.JFrame(), true,false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chon;
    private javax.swing.JButton dongy;
    private javax.swing.JButton huybo;
    private javax.swing.JComboBox nam;
    private javax.swing.JComboBox ngay;
    private javax.swing.JComboBox thang;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
