/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.com.Dialog;

import DataBase.HocSinh.Get;
import edu.com.CloseButton.CloseTabButton;
import edu.com.Panel.HocSinhA;
import edu.com.ThongTin;
import edu.com.XuLy;
import edu.com.upbang.XuLiXau;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author Venus
 */
public class NhapNghiPhep extends javax.swing.JDialog {

    public AutoSuggestor autoSuggestor1;
    public AutoSuggestor autoSuggestor;
    public JTabbedPane center;
    ArrayList<Integer> idNghiPhep;
    DataBase.HocSinh.NghiPhep a;
    /**
     * Creates new form NhapNghiPhep
     */
    public NhapNghiPhep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ArrayList nameClasses = new Get().GetNameClass();
        for(int i=0;i<nameClasses.size();i++)
            lop.addItem(nameClasses.get(i));
        addComponentListener(new ComponentAdapter() {
               
            @Override
            public void componentMoved(ComponentEvent e) {
                autoSuggestor.showPopUpWindow2();
                super.componentMoved(e); //To change body of generated methods, choose Tools | Templates.
            }
                
        });
        
        MakePopup();
        a= new DataBase.HocSinh.NghiPhep();
        new DataBase.SQLBangNghiPhep().BangNghiPhep(bangDSNghỉPhep);
        idNghiPhep = new ArrayList<Integer>();
        try{
        if (!bangDSNghỉPhep.getValueAt(0, 0).toString().equals("")) {
            XuLy.setID(idNghiPhep, bangDSNghỉPhep, 0);
            //resize(jTable4);
        }
        }
        catch(Exception ex)
        {}
        //add ten lop vao combobox
        
    }

    public void MakePopup(){
             autoSuggestor = new AutoSuggestor(ten, this, null, Color.WHITE.brighter(), Color.BLUE, Color.RED, 0.75f) {
                @Override
                boolean wordTyped(String typedWord) {

                    //create list for dictionary this in your case might be done via calling a method which queries db and returns results as arraylist
                    Get get = new Get();
                    String tenlop = lop.getSelectedItem().toString();
                    ArrayList words = get.GetNameStudent(tenlop);
                    setDictionary(words);
                    //addToDictionary("bye");//adds a single word

                    return super.wordTyped(typedWord);//now call super to check for any matches against newest dictionary
                }
            };
    }
    public boolean sosanhngaythang( String ngaybd, String ngaykt)
    {
        String []bd;
        String []kt;
        kt = ngaykt.split("-");
        bd = ngaybd.split("-");
        int datebd= Integer.parseInt(bd[0]);
        int monthbd= Integer.parseInt(bd[1]);
        int yearbd= Integer.parseInt(bd[2]);
        int datekt = Integer.parseInt(kt[0]);
        int monthkt= Integer.parseInt(kt[1]);
        int yearkt= Integer.parseInt(kt[2]);
        if(yearkt>yearbd) return true;
        else if(yearkt==yearbd&&monthkt>monthbd) return true;
        else if(yearkt==yearbd&&monthkt==monthbd&&datekt>datebd) return true;
        else return false;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangDSNghỉPhep = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lop = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ngay = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        thang = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        nam = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ngay1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        thang1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        nam1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        songayngay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhập Ngày Nghỉ Phép");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bangDSNghỉPhep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên HS", "Lớp", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Số Ngày", "Tình Trạng"
            }
        ));
        bangDSNghỉPhep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangDSNghỉPhepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangDSNghỉPhep);
        if (bangDSNghỉPhep.getColumnModel().getColumnCount() > 0) {
            bangDSNghỉPhep.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, 840, 251));

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopActionPerformed(evt);
            }
        });
        jPanel1.add(lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 0, 231, 25));

        jLabel3.setText("Lớp:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 80, -1));

        jLabel4.setText("Ngày bắt đầu:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 80, -1));

        ngay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(ngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 43, -1, -1));

        jLabel5.setText("Tháng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 46, -1, -1));

        thang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 43, -1, -1));

        jLabel6.setText("Năm");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 46, -1, -1));

        nam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel1.add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 43, -1, -1));

        jLabel7.setText("Ngày:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 46, 35, -1));

        jLabel9.setText("Ngày kết thúc:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 80, -1));

        jLabel10.setText("Ngày:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 77, 35, -1));

        ngay1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(ngay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 74, -1, -1));

        jLabel11.setText("Tháng");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 77, -1, -1));

        thang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(thang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 74, -1, -1));

        jLabel12.setText("Năm");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 77, -1, -1));

        nam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel1.add(nam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 74, -1, -1));

        jLabel13.setText("Số Ngày Nghỉ:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 80, -1));
        jPanel1.add(songayngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 105, 229, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nhập Ngày Nghỉ Phép");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        ten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 49, 172, -1));

        jLabel1.setText("Tên HS:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/xoa.jpg"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bangDSNghỉPhepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangDSNghỉPhepMouseClicked
        if(evt.getClickCount()==2){
            //map cac truong
            //tinh id hoc sinh
            String tenHocSinh = bangDSNghỉPhep.getValueAt(bangDSNghỉPhep.getSelectedRow(), 1).toString();
            String classes = bangDSNghỉPhep.getValueAt(bangDSNghỉPhep.getSelectedRow(), 2).toString();
            ArrayList infoHS = new Get().GetIdAndFacStudent(tenHocSinh, classes);
            int idHS = Integer.parseInt(infoHS.get(0).toString());

            //HocSinhA.idTemp = id;
            int a=-1;
            for (int i = 0; i < center.getTabCount(); i++) {
                if (tenHocSinh.equals(center.getTitleAt(i))) {
                    a += 1;
                    center.setSelectedIndex(i);
                }
            }
            if (a == -1) {

                HocSinhA aa = new HocSinhA(idHS);
                //add tab

                center.add(tenHocSinh, aa);
                center.setSelectedComponent(aa);
                new CloseTabButton(center,center.getComponentCount()-2);
            }
        }
    }//GEN-LAST:event_bangDSNghỉPhepMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = ten.getText();
        String classes = lop.getSelectedItem().toString();
        ArrayList infoHS = new Get().GetIdAndFacStudent(name, classes);
//        int idStudent = Integer.parseInt(infoHS.get(0).toString());
        int idTrungTam = Integer.parseInt(infoHS.get(1).toString());
        int idStudent = new DataBase.SQLXeBus().getIdStudent(name, classes);
        //them du lieu
            try{
                String datebd = ngay.getSelectedItem().toString() +"-"+ thang.getSelectedItem().toString() +"-"+nam.getSelectedItem().toString();
                String datekt = ngay1.getSelectedItem().toString() +"-"+ thang1.getSelectedItem().toString() +"-"+nam1.getSelectedItem().toString();
                
                if(sosanhngaythang(datebd, datekt))
                {
                    if(Integer.parseInt(songayngay.getText())>=1)
                    {
                        if(new DataBase.SQLXeBus().getIdStudent(ten.getText()+"", lop.getSelectedItem().toString())>0)
                        {
                        a.InsertNghiPhep(idStudent, idTrungTam,new XuLiXau().NamThangNgay(datebd),new XuLiXau().NamThangNgay(datekt),String.valueOf(Integer.parseInt(songayngay.getText())));
                        //load lai bang trong muon
                        new DataBase.SQLBangNghiPhep().BangNghiPhep(bangDSNghỉPhep);
                        
                        idNghiPhep = new ArrayList<Integer>();
                        try{
                        if (!bangDSNghỉPhep.getValueAt(0, 0).toString().equals("")) {
                        XuLy.setID(idNghiPhep, bangDSNghỉPhep, 0);
                        //resize(jTable4);
                        }
                        }
                        catch(Exception ex)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Nhập sai Số ngày");
                        }
                        }
                        else 
                        {
                                JOptionPane.showMessageDialog(rootPane, "Học sinh trên không có trong danh sách của lớp");
                        
                        }
                    }
                    else
                    {
                            JOptionPane.showMessageDialog(rootPane, "Số ngày phải lớn hơn 1");
                        
                            }
                }
                else
                {   
                        JOptionPane.showMessageDialog(rootPane, "Ngày bắt đầu nghỉ phải trước  ngày đi học lại");
        
                }
                
        }
        catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Nhập sai số ngày");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(bangDSNghỉPhep.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(rootPane ,"Hãy chọn một dòng cần xóa");
        }
        else{
            try
            {
               int click = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa đối tượng đã chọn không", null, JOptionPane.YES_NO_OPTION);
               if(click==JOptionPane.NO_OPTION){
                    return;
                }
            String name = bangDSNghỉPhep.getValueAt(bangDSNghỉPhep.getSelectedRow(), 1).toString();
            String classes = bangDSNghỉPhep.getValueAt(bangDSNghỉPhep.getSelectedRow(), 2).toString();
            
            ArrayList infoHS = new Get().GetIdAndFacStudent(name, classes);
         //   int idStudent = Integer.parseInt(infoHS.get(0).toString());
            int idTrungTam = Integer.parseInt(infoHS.get(1).toString());
            String datebd = bangDSNghỉPhep.getValueAt(bangDSNghỉPhep.getSelectedRow(), 3).toString();
            String datekt = bangDSNghỉPhep.getValueAt(bangDSNghỉPhep.getSelectedRow(), 4).toString();
            System.out.println(String.valueOf(idNghiPhep.get(bangDSNghỉPhep.getSelectedRow())));
            int idStudent = new DataBase.SQLXeBus().getIdStudent(name, classes);
            int b[] = null;
            for(int i=0;i<bangDSNghỉPhep.getSelectedRowCount();i++)
            {
                b=bangDSNghỉPhep.getSelectedRows();
            }
            for(int i=0;i<b.length;i++)
            {
            a.XoaNghiPhep(idStudent, datebd, datekt,idNghiPhep.get(b[i]));
            }       
            new DataBase.SQLBangNghiPhep().BangNghiPhep(bangDSNghỉPhep);
            idNghiPhep = new ArrayList<Integer>();
                    try{
                     if (!bangDSNghỉPhep.getValueAt(0, 0).toString().equals("")) {
                         XuLy.setID(idNghiPhep, bangDSNghỉPhep, 0);
                    //resize(jTable4);
                     }
                    }
                    catch(Exception ex)
                    {}

                        }
            catch(Exception ex)
            {}
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopActionPerformed
        MakePopup();
    }//GEN-LAST:event_lopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapNghiPhep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapNghiPhep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapNghiPhep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapNghiPhep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhapNghiPhep dialog = new NhapNghiPhep(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangDSNghỉPhep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox lop;
    private javax.swing.JComboBox nam;
    private javax.swing.JComboBox nam1;
    private javax.swing.JComboBox ngay;
    private javax.swing.JComboBox ngay1;
    private javax.swing.JTextField songayngay;
    private javax.swing.JTextField ten;
    private javax.swing.JComboBox thang;
    private javax.swing.JComboBox thang1;
    // End of variables declaration//GEN-END:variables
}
