/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.com.Dialog;

import DataBase.DataTable;
import edu.com.ThongTin;
import java.awt.TextField;
import java.awt.Toolkit;
import java.sql.Date;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author nguyen van cuong
 */
public class ThemSuaLop extends javax.swing.JDialog {
    private boolean button;
    private boolean themorsua;//cho biet la them lop hay sua lop
    private String oldName;
    public int idtrungtam;
    private int hshienco=0;
    /**
     * Creates new form ThemSuaLop
     */
    public ThemSuaLop(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
        trungtam.setSelectedIndex(ThongTin.trungtam-1);
        trungtam.setEnabled(false);

    }
     public ThemSuaLop(java.awt.Frame parent, boolean modal,Vector vector) {
        super(parent, modal);
        initComponents();
        System.out.println("goi duoc ca vector2");
        ten.setText(vector.get(0).toString());
        giaovien.setText(vector.get(4).toString());
        sohs.setValue(Integer.parseInt(vector.get(6).toString()));
        this.hshienco=Integer.parseInt(vector.get(5).toString());
        setSelectComboBox(ky, vector.get(3));
        setSelectComboBox(trinhdo, vector.get(2)); 
        DongY.setText("Chỉnh sửa");
        title.setText("Chỉnh sửa thông tin lớp");
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
     }
    private void setSelectComboBox(JComboBox x,Object obj){
        for(int i =0;i<x.getItemCount();i++){
            if(x.getItemAt(i).toString().equalsIgnoreCase(obj.toString())){
              x.setSelectedIndex(i);
              trungtam.setEnabled(false);
              break;
            } 
        }     
    }
    //set gia tri
    public void setKhoiName(String khoiname)
    {
        int id=0;
        if(khoiname.equals("NẮNG MAI (SUNSHINE)")) id=0;
        else if(khoiname.equals("TỔ ONG (BEEHIVE)")) id=1;
        else if(khoiname.equals("TỔ KÉN (CHRYSALIS)")) id=2;
        else  id=3;
        this.trinhdo.setSelectedIndex(id);
    }
    public void setOldName(String oldname)
    {
        this.oldName=oldname;
    }
    public void setThemSuaLop(boolean a)
    {
        this.themorsua=a;
    }
    //get cac gia tri 
    public boolean getButton()
    {
        return button;
    }
    public String getTenLop()
    {
        return ten.getText();
    }
    public String getGiaoVien()
    {
        return giaovien.getText();
    }
    public String getHocKy()
    {
        return ky.getSelectedItem().toString();
    }
    public String getKhoiHoc()
    {
        return trinhdo.getSelectedItem().toString();
    }
    public String getTrungTam()
    {
        return trungtam.getSelectedItem().toString();
    }
    public String getSoHS()
    {
        return sohs.getValue().toString();
    }
    //kiem tra ngay ket thuc va ngay bat dau
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        giaovien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sohs = new javax.swing.JSpinner();
        trinhdo = new javax.swing.JComboBox();
        ky = new javax.swing.JComboBox();
        trungtam = new javax.swing.JComboBox();
        DongY = new javax.swing.JButton();
        HuyBo = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên Lớp");

        jLabel2.setText("Giáo Viên");

        jLabel3.setText("Trung Tâm");

        jLabel4.setText("Tổng Học Sinh");

        jLabel5.setText("Kì Học");

        jLabel6.setText("Khối Học");

        sohs.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        trinhdo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NẮNG MAI (SUNSHINE)", "TỔ ONG (BEEHEVE)", "TỔ KÉN (CHRYSARYS)", "MẪU GIÁO (KINDERGENTEN)" }));

        ky.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        trungtam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Koala House Bà Triệu", "Koala House Hoàng Ngân", "Koala House Phan Kế Bình", "Koala House Nguyễn Huy Tự" }));

        DongY.setText("Thêm lớp");
        DongY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DongYMouseClicked(evt);
            }
        });
        DongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DongYActionPerformed(evt);
            }
        });

        HuyBo.setText("Hủy bỏ");
        HuyBo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HuyBoMouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Thêm lớp học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DongY, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ten)
                            .addComponent(sohs, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giaovien, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(trungtam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trinhdo, 0, 1, Short.MAX_VALUE)
                                    .addComponent(ky, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(trinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(giaovien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ky, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(sohs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trungtam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DongY, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DongYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DongYMouseClicked
        // TODO add your handling code here:
        DataBase.DataTable a = new DataTable();
        String tenlop= ten.getText();
        String tengiaovien=giaovien.getText();
        String hocky=ky.getSelectedItem().toString();
        String tentrinhdo=trinhdo.getSelectedItem().toString();
        String tentrungtam=trungtam.getSelectedItem().toString();
        String tonghs=sohs.getValue().toString();
        //doi ten khoi thanh so
        if(tentrinhdo.equals("NẮNG MAI (SUNSHINE)")) tentrinhdo="1";
        else if(tentrinhdo.equals("TỔ ONG (BEEHEVE)")) tentrinhdo="2";
        else if(tentrinhdo.equals("TỔ KÉN (CHRYSARYS)")) tentrinhdo="3";
        else tentrinhdo="4";
        //doi ten trung tam thanh so 
        if(tentrungtam.equals("Koala House Bà Triệu")) tentrungtam="1";
        else if (tentrungtam.equals("Koala House Hoàng Ngân")) tentrungtam="2";
        else if (tentrungtam.equals("Koala House Phan Kế Bình")) tentrungtam="3";
        else tentrungtam="4";
        //doi ten trang thai sang so
        this.idtrungtam=Integer.parseInt(tentrungtam);
       // kiem tra xem la co cho nao chua dien khong 
        if(tengiaovien!=null&&tenlop!=null)
        {
            if(themorsua==true)//them lop
            {
                  DataTable data= new DataTable();
                  if(tenlop.equals(""))
                  {
                    JOptionPane.showMessageDialog(null,"Tên lớp không được để trống!",null,JOptionPane.INFORMATION_MESSAGE);
          
                  }
                  else
                  {
                  if(data.ThemLop(tentrungtam, hocky, tentrinhdo, tenlop, tengiaovien, tonghs))
                    {
                        String message =String.format( "Bạn đã tạo thành công lớp mới");
                        JOptionPane.showMessageDialog( null, message );
                        button=true;
                        dispose();
                    }
                  }
            }
            else
            {
                if(tenlop.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Tên lớp không được để trống!",null,JOptionPane.INFORMATION_MESSAGE);
          
                }
                else
                {
                if(hshienco<=Integer.parseInt(tonghs))
                {    
                    DataTable data= new DataTable();
                    if(data.SuaLop(oldName,idtrungtam ,tentrungtam, hocky, tentrinhdo, tenlop, tengiaovien, tonghs))
                    {
                        String message =String.format( "Bạn đã chinh sua thanh cong");
                        JOptionPane.showMessageDialog( null, message );
                        button=true;
                        dispose();
                    }
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null,"Số lượng tổng học sinh lớn hơn học sinh hiện có trong lớp, mời bạn sửa đổi",null,JOptionPane.INFORMATION_MESSAGE);
        
                }
                }
             
            }
        }    
        else
        {
                String message =String.format( "lỗi tạo lớp, mời bạn xem lại dữ liệu");
                JOptionPane.showMessageDialog( null, message );
        }
        
       
       
    }//GEN-LAST:event_DongYMouseClicked

    private void HuyBoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuyBoMouseClicked
        // TODO add your handling code here:
        button=false;
        dispose();
    }//GEN-LAST:event_HuyBoMouseClicked

    private void DongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DongYActionPerformed
        // TODO add your handling code here:
                DataBase.DataTable a = new DataTable();
        String tenlop= ten.getText();
        String tengiaovien=giaovien.getText();
        String hocky=ky.getSelectedItem().toString();
        String tentrinhdo=trinhdo.getSelectedItem().toString();
        String tentrungtam=trungtam.getSelectedItem().toString();
        String tonghs=sohs.getValue().toString();
        //doi ten khoi thanh so
        if(tentrinhdo.equals("NẮNG MAI (SUNSHINE)")) tentrinhdo="1";
        else if(tentrinhdo.equals("TỔ ONG (BEEHEVE)")) tentrinhdo="2";
        else if(tentrinhdo.equals("TỔ KÉN (CHRYSARYS)")) tentrinhdo="3";
        else tentrinhdo="4";
        //doi ten trung tam thanh so 
        if(tentrungtam.equals("Koala House Bà Triệu")) tentrungtam="1";
        else if (tentrungtam.equals("Koala House Hoàng Ngân")) tentrungtam="2";
        else if (tentrungtam.equals("Koala House Phan Kế Bình")) tentrungtam="3";
        else tentrungtam="4";
        //doi ten trang thai sang so
        this.idtrungtam=Integer.parseInt(tentrungtam);
       // kiem tra xem la co cho nao chua dien khong 
        if(tengiaovien!=null&&tenlop!=null)
        {
            if(themorsua==true)//them lop
            {
                  DataTable data= new DataTable();
                  if(tenlop.equals(""))
                  {
                    JOptionPane.showMessageDialog(null,"Tên lớp không được để trống!",null,JOptionPane.INFORMATION_MESSAGE);
          
                  }
                  else
                  {
                  if(data.ThemLop(tentrungtam, hocky, tentrinhdo, tenlop, tengiaovien, tonghs))
                    {
                        String message =String.format( "Bạn đã tạo thành công lớp mới");
                        JOptionPane.showMessageDialog( null, message );
                        button=true;
                        dispose();
                    }
                  }
            }
            else
            {
                if(tenlop.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Tên lớp không được để trống!",null,JOptionPane.INFORMATION_MESSAGE);
          
                }
                else
                {
                if(hshienco<=Integer.parseInt(tonghs))
                {    
                    DataTable data= new DataTable();
                    if(data.SuaLop(oldName,idtrungtam ,tentrungtam, hocky, tentrinhdo, tenlop, tengiaovien, tonghs))
                    {
                        String message =String.format( "Bạn đã chinh sua thanh cong");
                        JOptionPane.showMessageDialog( null, message );
                        button=true;
                        dispose();
                    }
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null,"Số lượng tổng học sinh lớn hơn học sinh hiện có trong lớp, mời bạn sửa đổi",null,JOptionPane.INFORMATION_MESSAGE);
        
                }
                }
             
            }
        }    
        else
        {
                String message =String.format( "lỗi tạo lớp, mời bạn xem lại dữ liệu");
                JOptionPane.showMessageDialog( null, message );
        }
        
       
       

    }//GEN-LAST:event_DongYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSuaLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemSuaLop dialog = new ThemSuaLop(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DongY;
    private javax.swing.JButton HuyBo;
    private javax.swing.JTextField giaovien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox ky;
    private javax.swing.JSpinner sohs;
    private javax.swing.JTextField ten;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox trinhdo;
    private javax.swing.JComboBox trungtam;
    // End of variables declaration//GEN-END:variables
}
