/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.com.Panel;

import edu.com.CloseButton.CloseTabButton;
import edu.com.Dialog.BangHienThiTuanHe;
import edu.com.Dialog.ThemSuaDKHocHe;
import edu.com.XuLy;
import java.awt.Component;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Venus
 */
public class DKHocHe extends javax.swing.JPanel {
    private boolean isadmin=true;
    public ArrayList<Integer> id_hoche;
    public DefaultTableModel model,modelgoc;
    public JTabbedPane center;
    
    /**
     * Creates new form DKHocHe
     */
    public DKHocHe() {
        initComponents();
        modelgoc = (DefaultTableModel) jTable4.getModel();
        new DataBase.SQLkyhe().BandDanhSachDangKyHocHe(jTable4);
        id_hoche = new ArrayList<Integer>();
        try{
            if (!jTable4.getValueAt(0, 1).toString().equals("")) {
            XuLy.setID(id_hoche, jTable4, 0);
                resize(jTable4);
        }
        }
        catch(Exception ex)
        {
            jTable4.setModel(modelgoc);
        }
        
        
    }
     public void setNotAdmin()
    {
       them.setEnabled(false);
       sua.setEnabled(false);
       xoa.setEnabled(false);
       this.isadmin=false;
    }
   public void resize(JTable table)
   {
        table.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        int minwidth=80;
        for (int column = 0; column < table.getColumnCount(); column++)
        {
            TableColumn tableColumn = table.getColumnModel().getColumn(column);
            int preferredWidth = tableColumn.getMinWidth();
            int maxWidth = tableColumn.getMaxWidth();

            for (int row = 0; row < table.getRowCount(); row++)
            {
                TableCellRenderer cellRenderer = table.getCellRenderer(row, column);
                Component c = table.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + table.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width+10);

                //  We've exceeded the maximum width, no need to check other rows

                if (preferredWidth >= maxWidth)
                {
                    preferredWidth = maxWidth;
                    break;
                }
            }
            preferredWidth=Math.max(preferredWidth, minwidth);
            
            tableColumn.setPreferredWidth( preferredWidth );
            
        }
        TableColumn tableColumn = table.getColumnModel().getColumn(4);
        tableColumn.setPreferredWidth(150);
        tableColumn = table.getColumnModel().getColumn(0);
        tableColumn.setPreferredWidth(30);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_DSLop = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        them = new javax.swing.JLabel();
        sua = new javax.swing.JLabel();
        xoa = new javax.swing.JLabel();
        xemlich = new javax.swing.JLabel();
        textfield_timkiem = new javax.swing.JTextField();
        nam = new javax.swing.JComboBox();

        jTable4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Học Sinh", "Lớp", "Tuần Học", "Tổng Số Tuần", "Năm Học", "Trạng Thái", "Đánh Dấu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setRowHeight(30);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable4);

        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/them.jpg"))); // NOI18N
        them.setToolTipText("Thêm");
        them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themMouseClicked(evt);
            }
        });

        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/sua.JPG"))); // NOI18N
        sua.setToolTipText("Sửa");
        sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suaMouseClicked(evt);
            }
        });

        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/xoa.jpg"))); // NOI18N
        xoa.setToolTipText("Xóa");
        xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaMouseClicked(evt);
            }
        });

        xemlich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/chitiet.png"))); // NOI18N
        xemlich.setToolTipText("Xem Lịch Tuần Học");
        xemlich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xemlichMouseClicked(evt);
            }
        });

        textfield_timkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textfield_timkiem.setText("Tìm Kiếm");
        textfield_timkiem.setToolTipText("Tìm kiếm theo tên");
        textfield_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfield_timkiemMouseClicked(evt);
            }
        });
        textfield_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_timkiemActionPerformed(evt);
            }
        });
        textfield_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield_timkiemKeyReleased(evt);
            }
        });

        nam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất Cả", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        nam.setToolTipText("Hiển Thị Theo Năm");
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_DSLopLayout = new javax.swing.GroupLayout(Panel_DSLop);
        Panel_DSLop.setLayout(Panel_DSLopLayout);
        Panel_DSLopLayout.setHorizontalGroup(
            Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DSLopLayout.createSequentialGroup()
                .addComponent(them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xemlich)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
        );
        Panel_DSLopLayout.setVerticalGroup(
            Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DSLopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(xoa)
                        .addComponent(sua)
                        .addComponent(xemlich, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_timkiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_DSLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_DSLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_timkiemActionPerformed
        // TODO add your handling code here:
        new DataBase.SQLkyhe().BandDanhSachDangKyHocHe_TimKiem(jTable4,textfield_timkiem.getText());
        id_hoche = new ArrayList<Integer>();
        try{
            if (!jTable4.getValueAt(0, 1).toString().equals("")) {
                XuLy.setID(id_hoche, jTable4, 0);
                resize(jTable4);
            }
            else
            {
                //       jTable4.setAutoResizeMode( JTable.AUTO_RESIZE_ALL_COLUMNS );
                resize(jTable4);
            }
        }
        catch(Exception ex)
        {
            jTable4.setModel(modelgoc);
            resize(jTable4);
        }
    }//GEN-LAST:event_textfield_timkiemActionPerformed

    private void textfield_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfield_timkiemMouseClicked
        // TODO add your handling code here:
        textfield_timkiem.setText("");
    }//GEN-LAST:event_textfield_timkiemMouseClicked

    private void xemlichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xemlichMouseClicked
        // TODO add your handling code here:
        BangHienThiTuanHe banghoche= new BangHienThiTuanHe(null, true);
        banghoche.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
        banghoche.setVisible(true);

    }//GEN-LAST:event_xemlichMouseClicked

    private void xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaMouseClicked
        // TODO add your handling code here:
        if(!jTable4.getValueAt(0, 10).equals(""))
        {    

            if(isadmin)
            {
                model= (DefaultTableModel) jTable4.getModel();
                boolean flags = true;
                for (int i = model.getRowCount() - 1; i >= 0; i--) {
                    if ((Boolean) model.getValueAt(i,7) == true) {
                        flags = false;
                    }
                }
                if(!flags)
                {
                    int click = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa học sinh đã chọn không", null, JOptionPane.YES_NO_OPTION);
                    if(click==JOptionPane.NO_OPTION){
                        return;
                    }

                    boolean xoaorkhong;
                    DataBase.SQLkyhe data= new DataBase.SQLkyhe();
                    xoaorkhong=data.xoaDkHe(jTable4, 7,id_hoche);

                    new DataBase.SQLkyhe().BandDanhSachDangKyHocHe(jTable4);
                    id_hoche = new ArrayList<Integer>();
                    try
                    {

                        if (!jTable4.getValueAt(0, 1).toString().equals("")) {
                            XuLy.setID(id_hoche, jTable4, 0);
                            resize(jTable4);
                        }
                        else
                        {
                            resize(jTable4);
                        }
                    }
                    catch(Exception ex)
                    {

                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Bạn chưa chọn đối tượng cần chỉnh sửa",null,JOptionPane.INFORMATION_MESSAGE);

                }
            }
        }
    }//GEN-LAST:event_xoaMouseClicked

    private void suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suaMouseClicked
        if(!jTable4.getValueAt(0, 10).equals(""))
        {    
        
            if(isadmin)
            {
                int count =1, row=0;
                model=(DefaultTableModel) jTable4.getModel();
                for(int i = model.getRowCount()-1;i>=0;i--){
                    if((Boolean)model.getValueAt(i, 7)==true){
                        count--;
                        row = i;
                    }
                }
                if(count!=0){
                    if(count==1){
                        JOptionPane.showMessageDialog(null,"Bạn chưa chọn Học Sinh cần chỉnh sửa",null,JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Hệ thống chỉ cho phép chỉnh sửa một đối tượng tại một thời điểm",null,JOptionPane.INFORMATION_MESSAGE);
                        for(int i = model.getRowCount()-1;i>=0;i--){
                            model.setValueAt(false,i,7);
                        }
                    }
                    return;
                }
                Vector vec =  (Vector) model.getDataVector().elementAt(row);
                ThemSuaDKHocHe dkhoche= new ThemSuaDKHocHe(null, true,vec);
                dkhoche.setIdhoche(id_hoche.get(row));
                dkhoche.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
                dkhoche.setThemSuaLop(false);
                dkhoche.setVisible(true);

                //dkhoche.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
                new DataBase.SQLkyhe().BandDanhSachDangKyHocHe(jTable4);
                id_hoche = new ArrayList<Integer>();
                try
                {
                    if (!jTable4.getValueAt(0, 1).toString().equals("")) {
                        XuLy.setID(id_hoche, jTable4, 0);
                        resize(jTable4);
                    }
                }
                catch(Exception ex)
                {
                }
            }
            //ThemSuaLop lop = new ThemSuaLop(null, true, vec);
            /*
            if(lop.getButton()){
                model.setValueAt(lop.getTenLop(), row, 0);
                model.setValueAt(lop.getTrungTam(), row, 1);
                model.setValueAt(lop.getKhoiHoc(), row, 2);
                model.setValueAt(lop.getHocKy(), row, 3);
                model.setValueAt(lop.getGiaoVien(), row, 4);
                model.setValueAt(lop.getSoHS(), row, 5);
                model.setValueAt(lop.getTrangThai(), row, 7);
                model.setValueAt(false, row,8);
            }
            */
        }
    }//GEN-LAST:event_suaMouseClicked

    private void themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themMouseClicked
        // TODO add your handling code here:

        if(isadmin)
        {
            ThemSuaDKHocHe dkhoche= new ThemSuaDKHocHe(null, true);
            dkhoche.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);

            dkhoche.setThemSuaLop(true);
            dkhoche.setVisible(true);

            //receipts.setLocation(420, 20);
            //receipts.show();
            new DataBase.SQLkyhe().BandDanhSachDangKyHocHe(jTable4);
            id_hoche = new ArrayList<Integer>();
            try
            {
                if (!jTable4.getValueAt(0, 1).toString().equals("")) {
                    XuLy.setID(id_hoche, jTable4, 0);
                    resize(jTable4);
                }
            }
            catch(Exception ex)
            {}
        }
    }//GEN-LAST:event_themMouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        if (jTable4.getValueAt(0, 0).toString().equals("")) {
            return;
        }
        if (evt.getClickCount() == 2) {
            int row = jTable4.getSelectedRow();
            model=(DefaultTableModel) jTable4.getModel();
            model.setValueAt(false, row, 7);
            //map cac truong
            int a = -1;
            int id = 0;
            String tenHocSinh = jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString();
            String tenlop = jTable4.getValueAt(jTable4.getSelectedRow(), 2).toString();
            id = new DataBase.SQLkyhe().getIdStudent(tenHocSinh, tenlop);
            for (int i = 0; i < center.getTabCount(); i++) {
                if (tenHocSinh.equals(center.getTitleAt(i))) {
                    a += 1;
                    center.setSelectedIndex(i);
                }
            }
            if (a == -1) {
                //HocSinhA.idTemp = id;
                HocSinhA aa = new HocSinhA(id);
                center.add(model.getValueAt(row, 1).toString(), aa);
                center.setSelectedComponent(aa);
                new CloseTabButton(center, center.getComponentCount() - 2);
            }
        }
    }//GEN-LAST:event_jTable4MouseClicked

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
        
        try{
            String year= nam.getSelectedItem().toString();
        if(year.equals("Tất Cả"))
        {
            
            new DataBase.SQLkyhe().BandDanhSachDangKyHocHe(jTable4);
                    id_hoche = new ArrayList<Integer>();

        }
        else
        {
            new DataBase.SQLkyhe().BandDanhSachDangKyHocHe_TimKiemTheoNam(jTable4,year);
                    id_hoche = new ArrayList<Integer>();

        }
                    try{
                            if (!jTable4.getValueAt(0, 1).toString().equals("")) {
                            XuLy.setID(id_hoche, jTable4, 0);
                                resize(jTable4);
                        }
                        }
                        catch(Exception ex)
                        {
                            jTable4.setModel(modelgoc);
                        }

            resize(jTable4);
        }
        catch(Exception ex)
        {
            jTable4.setModel(modelgoc);
            resize(jTable4);
        }
    }//GEN-LAST:event_namActionPerformed

    private void textfield_timkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_timkiemKeyReleased
        // TODO add your handling code here:
        try{
            if(nam.getSelectedItem().toString().equals("Tất Cả"))
            {
                new DataBase.SQLkyhe().BandDanhSachDangKyHocHe_TimKiem(jTable4, textfield_timkiem.getText()+"");
             id_hoche = new ArrayList<Integer>();
        
            }
            else
            {
                new DataBase.SQLkyhe().BandDanhSachDangKyHocHe_TimKiemTheoNamVaTen(jTable4,nam.getSelectedItem().toString() , textfield_timkiem.getText()+"");
                         id_hoche = new ArrayList<Integer>();

            }
                try{
                    if (!jTable4.getValueAt(0, 1).toString().equals("")) {
                    XuLy.setID(id_hoche, jTable4, 0);
                        resize(jTable4);
                }
                }
                catch(Exception ex)
                {
                    jTable4.setModel(modelgoc);
                }

            resize(jTable4);
        }
        catch(Exception ex)
        {
            
            jTable4.setModel(modelgoc);
            resize(jTable4);
        }
    }//GEN-LAST:event_textfield_timkiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_DSLop;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable jTable4;
    private javax.swing.JComboBox nam;
    private javax.swing.JLabel sua;
    public javax.swing.JTextField textfield_timkiem;
    private javax.swing.JLabel them;
    private javax.swing.JLabel xemlich;
    private javax.swing.JLabel xoa;
    // End of variables declaration//GEN-END:variables
}
