/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.com.Panel;

import DataBase.DataTable;
import edu.com.CloseButton.CloseTabButton;
import edu.com.Dialog.chuyenlop;
import edu.com.XuLy;
import javax.swing.JComboBox;
import java.awt.Color;
import java.awt.Component;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Pham The Quyen
 */
public class DSHS extends javax.swing.JPanel {

    /**
     * Creates new form DSHS
     */
    public JTabbedPane center;
    ArrayList<Integer> id_students;
    int[] arrRows;
    private boolean isadmin = true;
    public JTable BangHS;
    public JComboBox ChonLoai;

    public DSHS() {
        initComponents();
        new DataBase.SQLDanhSachHocSinh().BangDanhSachHocSinh(DSHS, 1);
        id_students = new ArrayList<Integer>();
        if (DSHS.getValueAt(0, 0).toString().equals("")) {
            Count.setText("0");
        } else {
            Count.setText(String.valueOf(DSHS.getRowCount()));
            XuLy.setID(id_students, DSHS, 0);
        }
        arrRows = null;
        BangHS = DSHS;
        ChonLoai = LoaiHS;
    }

    public void setNotAdmin() {
        xoa.setEnabled(false);
        this.isadmin = false;
    }

    public void reload() {
        if (DSHS.getValueAt(0, 0).toString().equals("")) {
            Count.setText("0");
        } else {
            Count.setText(String.valueOf(DSHS.getRowCount()));
            XuLy.setID(id_students, DSHS, 0);
        }
        arrRows = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        DSHS = new javax.swing.JTable();
        Count = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        LoaiHS = new javax.swing.JComboBox();
        xoa = new javax.swing.JLabel();

        DSHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DSHS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Trình Độ", "Lớp", "Hình Thức Học", "Ngay Sinh"
            }
        ));
        DSHS.setRowHeight(30);
        DSHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSHSMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(DSHS);

        Count.setEditable(false);
        Count.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Count.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tổng Số HS:");

        LoaiHS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Học sinh đang học", "Học sinh nghỉ học", "Học sinh ra trường" }));
        LoaiHS.setMinimumSize(new java.awt.Dimension(114, 25));
        LoaiHS.setPreferredSize(new java.awt.Dimension(114, 25));
        LoaiHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiHSActionPerformed(evt);
            }
        });

        xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/xoa.jpg"))); // NOI18N
        xoa.setToolTipText("Xóa");
        xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(Count, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(LoaiHS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xoa)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Count, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoaiHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /*
     * setID dung de chuyen id hoc sinh sang so thu tu, từ số thứ tự thì chỉ số i-1 sẽ giúp truy suất trong mang id
     * giá trị Id_student tương ứng.
     */

    private void DSHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSHSMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2 && LoaiHS.getSelectedIndex() == 0) {
            int row = DSHS.getSelectedRow();
            //map cac truong
            int a = -1;
            int id = id_students.get(row);
            String tenHocSinh = DSHS.getValueAt(DSHS.getSelectedRow(), 1).toString();
            //HocSinhA.idTemp = id;
            for (int i = 0; i < center.getTabCount(); i++) {
                if (tenHocSinh.equals(center.getTitleAt(i))) {
                    a += 1;
                    center.setSelectedIndex(i);
                }
            }
            if (a == -1) {
                HocSinhA aa = new HocSinhA(id);
                center.add(DSHS.getModel().getValueAt(row, 1).toString(), aa);
                center.setSelectedComponent(aa);
                new CloseTabButton(center, center.getComponentCount() - 2);
            }
        } else {
            arrRows = DSHS.getSelectedRows();
        }
    }//GEN-LAST:event_DSHSMouseClicked

    private void LoaiHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiHSActionPerformed
        // TODO add your handling code here:
        switch (LoaiHS.getSelectedIndex()) {
            case 0:
                new DataBase.SQLDanhSachHocSinh().BangDanhSachHocSinh(DSHS, 1);
                break;
            case 1:
                new DataBase.SQLDanhSachHocSinh().BangDanhSachHocSinh(DSHS, 0);
                break;
            case 2:
                new DataBase.SQLDanhSachHocSinh().BangDanhSachHocSinh(DSHS, -1);
                break;
        }
        if (DSHS.getValueAt(0, 0).toString().equals("")) {
            Count.setText("0");
        } else {
            Count.setText(String.valueOf(DSHS.getRowCount()));
            XuLy.setID(id_students, DSHS, 0);
        }
        arrRows = null;

    }//GEN-LAST:event_LoaiHSActionPerformed

    private void xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaMouseClicked
        // TODO add your handling code here:
        if (isadmin) {
            if (DSHS.getValueAt(0, 0).toString().equals("")) {
                return;
            }
            boolean flags = true;
            for (int i = DSHS.getRowCount() - 1; i >= 0; i--) {
                if ((Boolean) DSHS.getValueAt(i, 6) == true) {
                    flags = false;
                }
            }
            if (flags) {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn học sinh cần xóa", null, JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int click = JOptionPane.showConfirmDialog(center, "Bạn có muốn xóa học sinh đã chọn không", null, JOptionPane.YES_NO_OPTION);
            if (click == JOptionPane.NO_OPTION) {
                return;
            }
            switch (LoaiHS.getSelectedIndex()) {
                case 0:
                    if (DSHS.getValueAt(0, 0).toString().equals("")) {
                        return;
                    }
                    for (int i = 0; i < DSHS.getRowCount(); i++) {
                        if (Boolean.parseBoolean(DSHS.getValueAt(i, 6).toString())) {
                            new DataBase.SQLLopX().xoaHocSinh(id_students.get(i));
                        }
                    }
                    new DataBase.SQLDanhSachHocSinh().BangDanhSachHocSinh(DSHS, 1);
                    break;
                case 1:
                    if (DSHS.getValueAt(0, 0).toString().equals("")) {
                        return;
                    }
                    for (int i = 0; i < DSHS.getRowCount(); i++) {
                        if (Boolean.parseBoolean(DSHS.getValueAt(i, 6).toString())) {
                            new DataBase.SQLDanhSachHocSinh().xoaHocSinh(id_students.get(i));
                        }
                    }
                    new DataBase.SQLDanhSachHocSinh().BangDanhSachHocSinh(DSHS, 0);
                    break;
                case 2:
                    if (DSHS.getValueAt(0, 0).toString().equals("")) {
                        return;
                    }
                    for (int i = 0; i < DSHS.getRowCount(); i++) {
                        if (Boolean.parseBoolean(DSHS.getValueAt(i, 6).toString())) {
                            new DataBase.SQLDanhSachHocSinh().xoaHocSinh(id_students.get(i));
                        }
                    }
                    new DataBase.SQLDanhSachHocSinh().BangDanhSachHocSinh(DSHS, -1);
                    break;
            }
            if (DSHS.getValueAt(0, 0).toString().equals("")) {
                Count.setText("0");
            } else {
                Count.setText(String.valueOf(DSHS.getRowCount()));
                XuLy.setID(id_students, DSHS, 0);
            }
        }
    }//GEN-LAST:event_xoaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Count;
    private javax.swing.JTable DSHS;
    private javax.swing.JComboBox LoaiHS;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel xoa;
    // End of variables declaration//GEN-END:variables
}
