/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.com.Panel;

import DataBase.ConnectData;
import DataBase.DataTable;
import edu.com.CloseButton.CloseTabButton;
import edu.com.Dialog.ThemSuaLop;
import edu.com.ListKoala;
import edu.com.ThongTin;
import edu.com.upbang.AddRowOfTable;
import edu.com.upbang.EditTable;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Pham The Quyen
 */
public class DSLop extends javax.swing.JPanel {

    /**
     * Creates new form DSLop
     */
   private int idtrungtams;
   public ListKoala listkoala;
   public JTabbedPane center;
   public  DefaultTableModel model;
   private boolean isadmin=true;
   public DSLop(int idtrungtam) {
        initComponents();
        try{
        new DataBase.DataTable().BangDanhSachLop(jTable4,idtrungtam);
        
        model = (DefaultTableModel) jTable4.getModel();
        resize(jTable4);
        }
        catch(Exception ex)
        {}
   }
   //set cac gia tri
   public void setIdTrungTam(int  a)
   {
       this.idtrungtams=a;
   }
   public void setNotAdmin()
   {
       Button_DSLop_ThemLop.setEnabled(false);
       Button_DSLop_SuaLop.setEnabled(false);
       Button_DSLop_Xoa.setEnabled(false);
       this.isadmin=false;
   }
   public void resize(JTable table)
   {
        table.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        int minwidth=80;
        for (int column = 0; column < table.getColumnCount(); column++)
        {
            TableColumn tableColumn = table.getColumnModel().getColumn(column);
            int preferredWidth = tableColumn.getMinWidth();
            int maxWidth = tableColumn.getMaxWidth();

            for (int row = 0; row < table.getRowCount(); row++)
            {
                TableCellRenderer cellRenderer = table.getCellRenderer(row, column);
                Component c = table.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + table.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width+10);

                //  We've exceeded the maximum width, no need to check other rows

                if (preferredWidth >= maxWidth)
                {
                    preferredWidth = maxWidth;
                    break;
                }
            }
            preferredWidth=Math.max(preferredWidth, minwidth);
            tableColumn.setPreferredWidth( preferredWidth );
            
        }
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_DSLop = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        Button_DSLop_ThemLop = new javax.swing.JLabel();
        Button_DSLop_SuaLop = new javax.swing.JLabel();
        Button_DSLop_Xoa = new javax.swing.JLabel();

        jTable4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên Lớp", "Trung tâm", "Trình độ", "Học kì", "Giáo Viên", "Ngày bắt đầu", "Ngày kết thúc", "Số học sinh", "Tối đa", "Trạng thái"
            }
        ));
        jTable4.setRowHeight(30);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(3).setMinWidth(50);
            jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable4.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        Button_DSLop_ThemLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/them.jpg"))); // NOI18N
        Button_DSLop_ThemLop.setToolTipText("Thêm");
        Button_DSLop_ThemLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_DSLop_ThemLopMouseClicked(evt);
            }
        });

        Button_DSLop_SuaLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/sua.JPG"))); // NOI18N
        Button_DSLop_SuaLop.setToolTipText("Sửa");
        Button_DSLop_SuaLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_DSLop_SuaLopMouseClicked(evt);
            }
        });

        Button_DSLop_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/xoa.jpg"))); // NOI18N
        Button_DSLop_Xoa.setToolTipText("Xóa");
        Button_DSLop_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_DSLop_XoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_DSLopLayout = new javax.swing.GroupLayout(Panel_DSLop);
        Panel_DSLop.setLayout(Panel_DSLopLayout);
        Panel_DSLopLayout.setHorizontalGroup(
            Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DSLopLayout.createSequentialGroup()
                .addComponent(Button_DSLop_ThemLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_DSLop_SuaLop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_DSLop_Xoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        Panel_DSLopLayout.setVerticalGroup(
            Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DSLopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button_DSLop_ThemLop)
                        .addComponent(Button_DSLop_SuaLop, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(Button_DSLop_Xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_DSLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_DSLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_DSLop_ThemLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_DSLop_ThemLopMouseClicked
        // TODO add your handling code here:
        try{
        if(isadmin)
        {
        ThemSuaLop lop = new ThemSuaLop(null,true);
        lop.setThemSuaLop(true);//day la them
        lop.setVisible(true);
        lop.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
        Vector vector = new Vector();
        if(lop.getButton()){
            vector.add(lop.getTenLop());
            vector.add(lop.getTrungTam());
            vector.add(lop.getKhoiHoc());
            vector.add(lop.getHocKy());
            vector.add(lop.getGiaoVien());
            vector.add(lop.getSoHS());
            vector.add(0);
            vector.add(false);
            model.addRow(vector);
            
        }
        new DataBase.DataTable().BangDanhSachLop(jTable4,ThongTin.trungtam);
        model=(DefaultTableModel) jTable4.getModel();
        resize(jTable4);
        
        listkoala.taoTree();
        }
        }
        catch(Exception ex)
        {}
    }//GEN-LAST:event_Button_DSLop_ThemLopMouseClicked

    private void Button_DSLop_SuaLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_DSLop_SuaLopMouseClicked
        try
        {
            if(isadmin)
            {
            int count =1, row=0;
            model=(DefaultTableModel) jTable4.getModel();
            for(int i = model.getRowCount()-1;i>=0;i--){
                if((Boolean)model.getValueAt(i, 7)==true){
                    count--;
                    row = i;
                }
            }
            if(count!=0){
                if(count==1){
                    JOptionPane.showMessageDialog(null,"Bạn chưa chọn lớp cần chỉnh sửa",null,JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Hệ thống chỉ cho phép chỉnh sửa một đối tượng tại một thời điểm",null,JOptionPane.INFORMATION_MESSAGE);
                    for(int i = model.getRowCount()-1;i>=0;i--){
                        model.setValueAt(false,i,7);
                   }
                }
                return;
            }
            Vector vec =  (Vector) model.getDataVector().elementAt(row);
            ThemSuaLop lop = new ThemSuaLop(null, true, vec);
            String oldname=model.getValueAt(row, 0).toString();
            String khoiname=model.getValueAt(row, 2).toString();
            lop.setOldName(oldname);
            lop.setKhoiName(khoiname);
            lop.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
            lop.setVisible(true);
            lop.setThemSuaLop(false);
            /*
            if(lop.getButton()){
                model.setValueAt(lop.getTenLop(), row, 0);
                model.setValueAt(lop.getTrungTam(), row, 1);
                model.setValueAt(lop.getKhoiHoc(), row, 2);
                model.setValueAt(lop.getHocKy(), row, 3);
                model.setValueAt(lop.getGiaoVien(), row, 4);
                model.setValueAt(lop.getSoHS(), row, 5);
                model.setValueAt(lop.getTrangThai(), row, 7);
                model.setValueAt(false, row,8);
            }
            */
            new DataBase.DataTable().BangDanhSachLop(jTable4,ThongTin.trungtam);
            model=(DefaultTableModel) jTable4.getModel();
            resize(jTable4);
            }
        }
        catch(Exception ex)
        {}
    }//GEN-LAST:event_Button_DSLop_SuaLopMouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount()==2){
            String tenlop=jTable4.getValueAt(jTable4.getSelectedRow(),0).toString();
            int a=-1;
            a=center.indexOfTab(tenlop);
            if(a==-1)
            {
            LopX aa = new LopX(tenlop);
            if(!ThongTin.isadmin)
               aa.setNotAdmin();
            aa.setName(tenlop);
            center.add(tenlop, aa);
            center.setSelectedComponent(aa);
            aa.center = center;
        new CloseTabButton(center,center.getComponentCount()-2);
            }
            else
            {
                center.setSelectedIndex(a);
            }
            
        }
    }//GEN-LAST:event_jTable4MouseClicked

    private void Button_DSLop_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_DSLop_XoaMouseClicked
        // TODO add your handling code here:
        try
        {
        if(isadmin)
        {
            boolean flags = true;
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                if ((Boolean) model.getValueAt(i, 7) == true) {
                    flags = false;
                }
            }
            if(!flags)
            {
                int click = JOptionPane.showConfirmDialog(center, "Bạn có muốn xóa lớp đã chọn không", null, JOptionPane.YES_NO_OPTION);
                if(click==JOptionPane.NO_OPTION){
                    return;
                }
                boolean xoaorkhong;
                DataBase.DataTable data= new DataTable();
                xoaorkhong=data.XoaLop(jTable4, 7);
                if(xoaorkhong)
                {
                EditTable edit= new EditTable();
                edit.removeManyRowOfTable(jTable4, 7);
                try{
                      new DataBase.DataTable().BangDanhSachLop(jTable4,ThongTin.trungtam);

                      model = (DefaultTableModel) jTable4.getModel();
                      resize(jTable4);
                      }
                      catch(Exception ex)
                      {}
                listkoala.taoTree();
                }
                model=(DefaultTableModel) jTable4.getModel();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Bạn chưa chọn lớp cần chỉnh sửa",null,JOptionPane.INFORMATION_MESSAGE);
   
            }
        }
        }
        catch(Exception ex)
        {}
    }//GEN-LAST:event_Button_DSLop_XoaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_DSLop_SuaLop;
    private javax.swing.JLabel Button_DSLop_ThemLop;
    private javax.swing.JLabel Button_DSLop_Xoa;
    private javax.swing.JPanel Panel_DSLop;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
