/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.com.Panel;

import DataBase.DataTable;
import edu.com.CloseButton.CloseTabButton;
import edu.com.Dialog.NghiPhep;
import edu.com.Dialog.ThemHS;
import edu.com.Dialog.chuyenlop;
import edu.com.Dialog.trongmuon;
import edu.com.ListKoala;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pham The Quyen
 */
public class LopX extends javax.swing.JPanel {
    
    private DefaultTableModel model;
    public JTabbedPane center;
    private int malop;
    /**
     * Creates new form LopX
     */
    public LopX() {
       initComponents();
       new DataBase.DataTable().BangDanhHSLop(1, lopx);
       model = (DefaultTableModel) lopx.getModel();
    }
    public LopX(String tenlop) {
        initComponents();
        setMaLopFromTen(tenlop);
        new DataBase.DataTable().BangDanhHSLop(malop,lopx);
        model = (DefaultTableModel) lopx.getModel();

     }
    public void setMaLop(int malop)
    {
        this.malop=malop;
    }
    public int getMaLop()
    {
        return malop;
    }
    public void setMaLopFromTen(String tenlop)
    {
        if (tenlop.equals("SUNSHINE_1")) this.malop=1;
        else if(tenlop.equals("SUNSHINE_2")) this.malop=2;
        else if(tenlop.equals("SUNSHINE_3")) this.malop=3;
        else if(tenlop.equals("BEEHIVE_1")) this.malop=4;
        else if(tenlop.equals("BEEHIVE_2")) this.malop=5;
        else if(tenlop.equals("BEEHIVE_3")) this.malop=6;
        else if(tenlop.equals("CHRYSALIS_1")) this.malop=7;
        else if(tenlop.equals("CHRYSALIS_1")) this.malop=8;
        else if(tenlop.equals("KINDERGARTEN_1")) this.malop=9;
        else this.malop=10;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        lopx = new javax.swing.JTable();
        them = new javax.swing.JLabel();
        sua = new javax.swing.JLabel();
        xoa = new javax.swing.JLabel();
        chuyenlop = new javax.swing.JButton();
        loc = new javax.swing.JComboBox();
        nghi = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        chitiet = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        lopx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Số HS", "Họ Tên", "Ngày Sinh", "Hình Thức Học", "SĐT", "Người Đại Diện", "Đánh Dấu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        lopx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lopxMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lopx);

        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/them.jpg"))); // NOI18N
        them.setToolTipText("Thêm");
        them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themMouseClicked(evt);
            }
        });

        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/sua.JPG"))); // NOI18N
        sua.setToolTipText("Sửa");
        sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suaMouseClicked(evt);
            }
        });

        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/xoa.jpg"))); // NOI18N
        xoa.setToolTipText("Xóa");
        xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaMouseClicked(evt);
            }
        });

        chuyenlop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chuyenlop.setText("Chuyển Lớp");
        chuyenlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyenlopActionPerformed(evt);
            }
        });

        loc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tât cả", "Chính quy", "Khách", "Đóng tiền đầy đủ", "Nợ" }));
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });

        nghi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nghi.setText("Danh Sách Nghỉ Phép");
        nghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nghiActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        chitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/chitiet.png"))); // NOI18N
        chitiet.setToolTipText("Xem chi tiết");
        chitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chitietMouseClicked(evt);
            }
        });

        jButton1.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chitiet)
                .addGap(191, 191, 191)
                .addComponent(chuyenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(nghi)
                .addGap(44, 44, 44)
                .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sua)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chuyenlop)
                                    .addComponent(nghi)
                                    .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(xoa))
                            .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chitiet))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lopxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lopxMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int row = lopx.getSelectedRow();
            model.setValueAt(false, row, 6);
            //map cac truong
            String idStudent = lopx.getValueAt(row, 0).toString();
            int id = Integer.parseInt(idStudent);
            DataTable a = new DataTable();
            ArrayList info,lateday;
            info = a.HocSinhA1(id);
            lateday = a.LateDay(id);
            HocSinhA.tenHS = (String) info.get(1);
            HocSinhA.tenNguoiDaiDien = (String) info.get(4);
            HocSinhA.ngaySinh = (String) info.get(2);
            HocSinhA.SDT = (String) info.get(3);
            HocSinhA.hinhThucHoc = (String) info.get(7);
            HocSinhA.lop = (String) info.get(6);
            HocSinhA.trinhDo = (String) info.get(5);
            HocSinhA.trungTam = (String) info.get(8);
            HocSinhA.soNgayTrongMuon = String.valueOf(lateday.size());
            //add tab
            HocSinhA aa = new HocSinhA();
            aa.id = id;
            aa.lateday = lateday;
            center.add(model.getValueAt(row, 1).toString(), aa);
            center.setSelectedComponent(aa);
            new CloseTabButton(center,center.getComponentCount()-2);
        }
    }//GEN-LAST:event_lopxMouseClicked

    private void themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themMouseClicked
        // TODO add your handling code here:
        ThemHS hs = new ThemHS(ListKoala.frame, true);
        hs.setVisible(true);
        if(hs.getButton()){
            Vector vector = new Vector();
            vector.add(model.getRowCount()+1);
            vector.add(hs.getTenHS());
            vector.add(hs.getNgaySinh());
            vector.add(hs.getHinhThuc());
            vector.add(hs.getDienThoai());
            vector.add(hs.getDaiDien());
            vector.add(false);
            model.addRow(vector);
        }
    }//GEN-LAST:event_themMouseClicked

    private void suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suaMouseClicked
        // TODO add your handling code here:
        int count =1, row=0;
        for(int i = model.getRowCount()-1;i>=0;i--){
            if((Boolean)model.getValueAt(i, 6)==true){
                count--;
                row = i;
            }
        }
        if(count!=0){
            if(count==1){
                JOptionPane.showMessageDialog(null,"Bạn chưa chọn hoc sinh cần chỉnh sửa",null,JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"Hệ thống chỉ cho phép chỉnh sửa một đối tượng tại một thời điểm",null,JOptionPane.INFORMATION_MESSAGE);
                for(int i = model.getRowCount()-1;i>=0;i--){
             model.setValueAt(false,i,6);
               }
            }
            return;
        }
        Vector vec =  (Vector) model.getDataVector().elementAt(row);
        ThemHS hs = new ThemHS(null, true, vec);
        hs.setVisible(true);
        if(hs.getButton()){
            model.setValueAt(hs.getTenHS(), row, 1);
            model.setValueAt(hs.getNgaySinh(), row, 2);
            model.setValueAt(hs.getHinhThuc(), row, 3);
            model.setValueAt(hs.getDienThoai(), row, 4);
            model.setValueAt(hs.getDaiDien(), row, 5);
            model.setValueAt(false, row, 6);
        }
    }//GEN-LAST:event_suaMouseClicked

    private void chuyenlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyenlopActionPerformed
        // TODO add your handling code here:
        int count=0;
        for(int i = model.getRowCount()-1;i>=0;i--){
            if((Boolean)model.getValueAt(i, 6)==true){
                count++;
            }
        }
        if(count==0){
            return;
        }
        chuyenlop chuyen = new chuyenlop(null, true,getName());
        chuyen.setVisible(true);
        for(int i = model.getRowCount()-1;i>=0;i--){
            if((Boolean)model.getValueAt(i, 6)==true){
                model.removeRow(i);
            }
        }
        
    }//GEN-LAST:event_chuyenlopActionPerformed

    private void nghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nghiActionPerformed
        // TODO add your handling code here:
        NghiPhep nghi = new NghiPhep(null, true);
        nghi.setTitle("Danh sách nghi phép lớp "+this.getName());
        nghi.setVisible(true);
         
    }//GEN-LAST:event_nghiActionPerformed

    private void xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaMouseClicked
        // TODO add your handling code here:
        for(int i = model.getRowCount()-1;i>=0;i--){
            if((Boolean)model.getValueAt(i, 6)==true){
                model.removeRow(i);
            }
        }
    }//GEN-LAST:event_xoaMouseClicked

    private void chitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chitietMouseClicked
        // TODO add your handling code here:
        for(int i = model.getRowCount()-1;i>=0;i--){
            if((Boolean)model.getValueAt(i, 6)==true){
                model.setValueAt(false, i, 6);
                String idStudent = lopx.getValueAt(i, 0).toString();
            int id = Integer.parseInt(idStudent);
            DataTable a = new DataTable();
            ArrayList info,lateday;
            info = a.HocSinhA1(id);
            lateday = a.LateDay(id);
            HocSinhA.tenHS = (String) info.get(1);
            HocSinhA.tenNguoiDaiDien = (String) info.get(4);
            HocSinhA.ngaySinh = (String) info.get(2);
            HocSinhA.SDT = (String) info.get(3);
            HocSinhA.hinhThucHoc = (String) info.get(7);
            HocSinhA.lop = (String) info.get(6);
            HocSinhA.trinhDo = (String) info.get(5);
            HocSinhA.trungTam = (String) info.get(8);
            HocSinhA.soNgayTrongMuon = String.valueOf(lateday.size());
            //add tab
            HocSinhA aa = new HocSinhA();
            aa.id = id;
            aa.lateday = lateday;
            center.add(model.getValueAt(i, 1).toString(), aa);
            center.setSelectedComponent(aa);
            new CloseTabButton(center,center.getComponentCount()-2);
            }
        }
    }//GEN-LAST:event_chitietMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        // TODO add your handling code here:
        switch (loc.getSelectedIndex()){
            case 0:
                new DataBase.DataTable().BangDanhHSLop(1, lopx);
                model = (DefaultTableModel) lopx.getModel();
                break;
            case 1:
                new DataBase.DataTable().BangDanhHSLop_ChinhQuy(1, lopx);
                model = (DefaultTableModel) lopx.getModel();
                break;
            case 2:
                new DataBase.DataTable().BangDanhHSLop_Khach(1, lopx);
                model = (DefaultTableModel) lopx.getModel();
                break;
            case 3:
                new DataBase.DataTable().BangDanhSachHSDongDuPhi(1, lopx);
                model = (DefaultTableModel) lopx.getModel();
                break;
            case 4:
                new DataBase.DataTable().BangDanhSachHocSinhNoPhi(1, lopx);
                model = (DefaultTableModel) lopx.getModel();
                break;
        }
    }//GEN-LAST:event_locActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chitiet;
    private javax.swing.JButton chuyenlop;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox loc;
    private javax.swing.JTable lopx;
    private javax.swing.JButton nghi;
    private javax.swing.JLabel sua;
    private javax.swing.JLabel them;
    private javax.swing.JLabel xoa;
    // End of variables declaration//GEN-END:variables
}
