/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.com.Panel;

import DataBase.DataTable;
import edu.com.Dialog.DSXeBus;
import edu.com.Dialog.ThemSuaLop;
import edu.com.ThongTin;
import edu.com.XuLy;
import edu.com.upbang.EditTable;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Venus
 */
public class XeBus extends javax.swing.JPanel {

    private boolean isadmin=true;
    private DefaultTableModel model;
    ArrayList<Integer> id_xebus;
    /**
     * Creates new form XeBus
     */
    public XeBus() {
        initComponents();
       // System.out.println("da den doan nay");
        new DataBase.SQLXeBus().BandDanhSachXeBus(jTable4);
        id_xebus = new ArrayList<Integer>();
        try{
        if (!jTable4.getValueAt(0, 0).toString().equals("")) {
            XuLy.setID(id_xebus, jTable4, 0);
        }
        }
        catch(Exception ex)
        {}
        //System.out.println("da den doan sau nay nua co");
        
    }
    public void setNotAdmin()
    {
       them.setEnabled(false);
       sua.setEnabled(false);
       xoa.setEnabled(false);
       this.isadmin=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_DSLop = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        them = new javax.swing.JLabel();
        sua = new javax.swing.JLabel();
        xoa = new javax.swing.JLabel();

        jTable4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Học Sinh", "Lớp", "Địa Chỉ", "Số Điện Thoại", "Số Lượt Đi", "Tiền Xe", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Ghi Chú", "Đánh Dấu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setRowHeight(30);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setMinWidth(30);
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable4.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable4.getColumnModel().getColumn(2).setMinWidth(120);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTable4.getColumnModel().getColumn(2).setMaxWidth(130);
            jTable4.getColumnModel().getColumn(4).setMinWidth(120);
            jTable4.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTable4.getColumnModel().getColumn(4).setMaxWidth(130);
            jTable4.getColumnModel().getColumn(5).setMinWidth(70);
            jTable4.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTable4.getColumnModel().getColumn(5).setMaxWidth(80);
            jTable4.getColumnModel().getColumn(7).setMinWidth(100);
            jTable4.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(7).setMaxWidth(120);
        }

        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/them.jpg"))); // NOI18N
        them.setToolTipText("Thêm");
        them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themMouseClicked(evt);
            }
        });

        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/sua.JPG"))); // NOI18N
        sua.setToolTipText("Sửa");
        sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suaMouseClicked(evt);
            }
        });

        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/xoa.jpg"))); // NOI18N
        xoa.setToolTipText("Xóa");
        xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_DSLopLayout = new javax.swing.GroupLayout(Panel_DSLop);
        Panel_DSLop.setLayout(Panel_DSLopLayout);
        Panel_DSLopLayout.setHorizontalGroup(
            Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DSLopLayout.createSequentialGroup()
                .addGroup(Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DSLopLayout.createSequentialGroup()
                        .addComponent(them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xoa)
                        .addGap(0, 988, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_DSLopLayout.setVerticalGroup(
            Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DSLopLayout.createSequentialGroup()
                .addGroup(Panel_DSLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them)
                    .addComponent(sua)
                    .addComponent(xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_DSLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_DSLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:

       
    }//GEN-LAST:event_jTable4MouseClicked

    private void themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themMouseClicked
        // TODO add your handling code here:
        if(isadmin)
        {
            
            DSXeBus  dsbus= new DSXeBus(null, true);
            dsbus.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
            
            dsbus.setThemSuaLop(true);
            dsbus.setVisible(true);
            new DataBase.SQLXeBus().BandDanhSachXeBus(jTable4);
            id_xebus = new ArrayList<Integer>();
            try{
                if (!jTable4.getValueAt(0, 0).toString().equals("")) {
                XuLy.setID(id_xebus, jTable4, 0);
                }
                }
                catch(Exception ex)
                {}
        }
    }//GEN-LAST:event_themMouseClicked

    private void suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suaMouseClicked
        
        if(isadmin)
        {
        int count =1, row=0;
        model=(DefaultTableModel) jTable4.getModel();
        try{
        for(int i = model.getRowCount()-1;i>=0;i--){
            if((Boolean)model.getValueAt(i, 10)==true){
                count--;
                row = i;
            }
        }
        }
        catch(Exception ex)
        {
        
        }
        if(count!=0){
            if(count==1){
                JOptionPane.showMessageDialog(null,"Bạn chưa chọn Học Sinh cần chỉnh sửa",null,JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"Hệ thống chỉ cho phép chỉnh sửa một đối tượng tại một thời điểm",null,JOptionPane.INFORMATION_MESSAGE);
                for(int i = model.getRowCount()-1;i>=0;i--){
                    model.setValueAt(false,i,10);
               }
            }
            return;
        }
        Vector vec =  (Vector) model.getDataVector().elementAt(row);
        DSXeBus  dsbus= new DSXeBus(null, true,vec);
        dsbus.setThemSuaLop(false);
        dsbus.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-200,Toolkit.getDefaultToolkit().getScreenSize().height/2-200);
        
        dsbus.setVisible(true);
        
        new DataBase.SQLXeBus().BandDanhSachXeBus(jTable4);
            id_xebus = new ArrayList<Integer>();
            try{
            if (!jTable4.getValueAt(0, 0).toString().equals("")) {
                XuLy.setID(id_xebus, jTable4, 0);
            }
            }
            catch(Exception ex)
            {}
        //ThemSuaLop lop = new ThemSuaLop(null, true, vec);
        /*
        if(lop.getButton()){
            model.setValueAt(lop.getTenLop(), row, 0);
            model.setValueAt(lop.getTrungTam(), row, 1);
            model.setValueAt(lop.getKhoiHoc(), row, 2);
            model.setValueAt(lop.getHocKy(), row, 3);
            model.setValueAt(lop.getGiaoVien(), row, 4);
            model.setValueAt(lop.getSoHS(), row, 5);
            model.setValueAt(lop.getTrangThai(), row, 7);
            model.setValueAt(false, row,8);
        }
        */
        }
    }//GEN-LAST:event_suaMouseClicked

    private void xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoaMouseClicked
        // TODO add your handling code here:
       
        boolean xoaorkhong;
        DataBase.SQLXeBus data= new DataBase.SQLXeBus();
        xoaorkhong=data.xoaxebus(jTable4, 10);
       
          new DataBase.SQLXeBus().BandDanhSachXeBus(jTable4);
            id_xebus = new ArrayList<Integer>();
            try{
                if (!jTable4.getValueAt(0, 0).toString().equals("")) {
                XuLy.setID(id_xebus, jTable4, 0);
                }
                }
            catch(Exception ex)
            {}
        
    }//GEN-LAST:event_xoaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_DSLop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel sua;
    private javax.swing.JLabel them;
    private javax.swing.JLabel xoa;
    // End of variables declaration//GEN-END:variables
}
